Traceback (most recent call last):
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skorczewskit\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cardata = np.loadtxt("./engine_mpg.csv", delimiter=",",skiprows=3,usecols=(2,3))
engine = cardata[:,0]
mpg = cardata[:,1]
plt.plot(engine,mpg,'r.');
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOSError[0m                                   Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m cardata [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mloadtxt[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m./engine_mpg.csv[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdelimiter[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m,[39;49m[38;5;124;43m"[39;49m[43m,[49m[43mskiprows[49m[38;5;241;43m=[39;49m[38;5;241;43m3[39;49m[43m,[49m[43musecols[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m2[39;49m[43m,[49m[38;5;241;43m3[39;49m[43m)[49m[43m)[49m
[0;32m      2[0m engine [38;5;241m=[39m cardata[:,[38;5;241m0[39m]
[0;32m      3[0m mpg [38;5;241m=[39m cardata[:,[38;5;241m1[39m]

File [1;32m~\Anaconda3\lib\site-packages\numpy\lib\npyio.py:1067[0m, in [0;36mloadtxt[1;34m(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)[0m
[0;32m   1065[0m     fname [38;5;241m=[39m os_fspath(fname)
[0;32m   1066[0m [38;5;28;01mif[39;00m _is_string_like(fname):
[1;32m-> 1067[0m     fh [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlib[49m[38;5;241;43m.[39;49m[43m_datasource[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrt[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m)[49m
[0;32m   1068[0m     fencoding [38;5;241m=[39m [38;5;28mgetattr[39m(fh, [38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mlatin1[39m[38;5;124m'[39m)
[0;32m   1069[0m     fh [38;5;241m=[39m [38;5;28miter[39m(fh)

File [1;32m~\Anaconda3\lib\site-packages\numpy\lib\_datasource.py:193[0m, in [0;36mopen[1;34m(path, mode, destpath, encoding, newline)[0m
[0;32m    156[0m [38;5;124;03m"""[39;00m
[0;32m    157[0m [38;5;124;03mOpen `path` with `mode` and return the file object.[39;00m
[0;32m    158[0m 
[1;32m   (...)[0m
[0;32m    189[0m 
[0;32m    190[0m [38;5;124;03m"""[39;00m
[0;32m    192[0m ds [38;5;241m=[39m DataSource(destpath)
[1;32m--> 193[0m [38;5;28;01mreturn[39;00m [43mds[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m,[49m[43m [49m[43mnewline[49m[38;5;241;43m=[39;49m[43mnewline[49m[43m)[49m

File [1;32m~\Anaconda3\lib\site-packages\numpy\lib\_datasource.py:533[0m, in [0;36mDataSource.open[1;34m(self, path, mode, encoding, newline)[0m
[0;32m    530[0m     [38;5;28;01mreturn[39;00m _file_openers[ext](found, mode[38;5;241m=[39mmode,
[0;32m    531[0m                               encoding[38;5;241m=[39mencoding, newline[38;5;241m=[39mnewline)
[0;32m    532[0m [38;5;28;01melse[39;00m:
[1;32m--> 533[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m([38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m not found.[39m[38;5;124m"[39m [38;5;241m%[39m path)

[1;31mOSError[0m: ./engine_mpg.csv not found.
OSError: ./engine_mpg.csv not found.

